import { generateExercise } from './src/utils/gemini.js';

async function test() {
  console.log('Testing Gemini API...');
  try {
    const result = await generateExercise('', 'beginner', 'capitalization');
    console.log('Result:', JSON.stringify(result, null, 2));
    if (result.aiGenerated) {
      console.log('\nSuccess! Text was generated by the AI.');
    } else {
      console.log('\nFallback used! Returned a mock exercise.');
    }
  } catch (error) {
    console.error('Error:', error);
  }
}

test();
